name: Daily Commit

on:
  schedule:
    - cron: '10 3 * * *'  # Runs daily at 03:10 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git config for 23f3003724@ds.study.iitm.ac.in
      run: |
        git config user.name "devsync-bot"
        git config user.email "gvedika702@gmail.com"

    - name: Make dummy change
      run: |
        echo "Daily update: $(date -u)" >> daily-log.txt

    - name: Commit and Push
      run: |
        git add daily-log.txt
        git commit -m "Automated daily update: $(date -u)" || echo "No changes to commit"
        git push
